### ISSUE TITLE
[JA] Pre-release Task Board

### ISSUE THREAD

**Issue by foxytanuki** [mycel-labs/frontend#26]
#### `start.lazy.tsx`

- [x] `createUser`の実行時にreferralを処理し、成功後に`localStorage`の`refCode`をクリア (createUser時の署名も含む) #23 #25 

- [x] referral DBをチェックし、既にreferralにユーザーが存在するかどうかに応じて`/home`にリダイレクトするか判定 #23 #28

#### `_app.tsx`

- [x] referral DBをチェックし、既にreferralにユーザーが存在するかどうかに応じて`/start`にリダイレクトするか判定 #23 #28

#### `_app.referral.lazy.tsx`

- [x] `queryGetReferralCodeByIssuerUserId`を使用して`refCode`を発行 #23 #27

### Faucet, Prize

- [ ]  https://github.com/mycel-labs/frontend/pull/22 のreview, 修正及び追加実装見積もり #22
